name: Continuous Integration and Deployment

on:
 push:
   branches:
     - main
 workflow_dispatch:

jobs:
 deploy:
   runs-on: ubuntu-24.04
   steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Google Auth
       id: auth
       uses: 'google-github-actions/auth@v2'
       with:
         credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

     - name: Setup Cloud SDK
       uses: 'google-github-actions/setup-gcloud@v2'

     - name: Upload Demo Website
       run: |
         gcloud components install gsutil
         gsutil -m cp 404.html gs://demo.telecomsteve.com/
         gsutil -m cp index.html gs://demo.telecomsteve.com/
         gsutil -m cp portfolio.html gs://demo.telecomsteve.com/
         gsutil -m cp research.html gs://demo.telecomsteve.com/
         gsutil -m cp resume.html gs://demo.telecomsteve.com/
         gsutil -m cp sidenav.html gs://demo.telecomsteve.com/
         gsutil -m cp blog.html gs://demo.telecomsteve.com/
         gsutil -m cp -r blog-posts gs://demo.telecomsteve.com/
         gsutil -m cp -r css gs://demo.telecomsteve.com/
         gsutil -m cp -r img gs://demo.telecomsteve.com/
         gsutil -m cp -r js gs://demo.telecomsteve.com/
         gsutil -m cp LICENSE gs://demo.telecomsteve.com/
         gsutil -m cp README.md gs://demo.telecomsteve.com/
         gsutil web set -m index.html -e 404.html gs://demo.telecomsteve.com/
         gsutil -m acl ch -r -u AllUsers:R gs://demo.telecomsteve.com/

     - name: Upload Production Website  
       run: |
         gsutil -m cp -r examples/telecomsteve/* gs://telecomsteve.com/
         gsutil web set -m index.html -e 404.html gs://telecomsteve.com/
         gsutil -m acl ch -r -u AllUsers:R gs://telecomsteve.com/