name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }} 
          
      - name: Upload to Google Cloud Storage
        run: |
          # Ensure gsutil is installed
          gcloud components install gsutil
          
          # Copy contents recursively from .examples/telecomsteve to GCS bucket
          gsutil -m cp -r .examples/telecomsteve/* gs://telecomsteve-website/
          
          # Set website configuration
          gsutil web set -m index.html gs://telecomsteve-website/
          
          # Make objects public
          gsutil -m acl ch -r -u AllUsers:R gs://telecomsteve-website/